//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcModpackInstaller.Resources.Localizations.MessageBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcModpackInstaller.Resources.Localizations.MessageBox.MessageBox", typeof(MessageBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the list?.
        /// </summary>
        internal static string MessageBoxClearList {
            get {
                return ResourceManager.GetString("MessageBoxClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared..
        /// </summary>
        internal static string MessageBoxClearSuccessful {
            get {
                return ResourceManager.GetString("MessageBoxClearSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} from the list?.
        /// </summary>
        internal static string MessageBoxDeleteFromList {
            get {
                return ResourceManager.GetString("MessageBoxDeleteFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Minecraft cannot be empty..
        /// </summary>
        internal static string MessageBoxDotMinecraftPathEmpty {
            get {
                return ResourceManager.GetString("MessageBoxDotMinecraftPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path to Minecraft does not exist..
        /// </summary>
        internal static string MessageBoxDotMinecraftPathNotFound {
            get {
                return ResourceManager.GetString("MessageBoxDotMinecraftPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File named {0} already exists in destination folder. Installation of this mod will be skipped..
        /// </summary>
        internal static string MessageBoxFileAlreadyExists {
            get {
                return ResourceManager.GetString("MessageBoxFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in the list..
        /// </summary>
        internal static string MessageBoxFileAlreadyInList {
            get {
                return ResourceManager.GetString("MessageBoxFileAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a .jar or .zip archive..
        /// </summary>
        internal static string MessageBoxFileNotJarOrZip {
            get {
                return ResourceManager.GetString("MessageBoxFileNotJarOrZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete contents of Minecraft folder?.
        /// </summary>
        internal static string MessageBoxGeneralCleaningConfirmation {
            get {
                return ResourceManager.GetString("MessageBoxGeneralCleaningConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation is complete..
        /// </summary>
        internal static string MessageBoxInstallationSuccessful {
            get {
                return ResourceManager.GetString("MessageBoxInstallationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This .jar is a plugin for Minecraft server..
        /// </summary>
        internal static string MessageBoxJarIsPlugin {
            get {
                return ResourceManager.GetString("MessageBoxJarIsPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File named {0} already exists in destination folder. Do you wish to overwrite file?.
        /// </summary>
        internal static string MessageBoxOverwriteConfirmation {
            get {
                return ResourceManager.GetString("MessageBoxOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with detecting if the file {0} is a mod. Are you sure, that you want to add this file to the list?.
        /// </summary>
        internal static string MessageBoxPotentiallyNotMod {
            get {
                return ResourceManager.GetString("MessageBoxPotentiallyNotMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found in source directory. Installation of this mod will be skipped..
        /// </summary>
        internal static string MessageBoxSourceFileNotFound {
            get {
                return ResourceManager.GetString("MessageBoxSourceFileNotFound", resourceCulture);
            }
        }
    }
}
