//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcModpackInstaller.Resources.Localizations.Status {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcModpackInstaller.Resources.Localizations.Status.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0}....
        /// </summary>
        internal static string StatusAddingToList {
            get {
                return ResourceManager.GetString("StatusAddingToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .minecraft was found successfully..
        /// </summary>
        internal static string StatusDotMinecraftFound {
            get {
                return ResourceManager.GetString("StatusDotMinecraftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .minecraft wasn&apos;t found! Please specify folder where Minecraft is installed..
        /// </summary>
        internal static string StatusDotMinecraftNotFound {
            get {
                return ResourceManager.GetString("StatusDotMinecraftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File named {0} already exists in destination folder..
        /// </summary>
        internal static string StatusFileAlreadyExists {
            get {
                return ResourceManager.GetString("StatusFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string StatusGeneric {
            get {
                return ResourceManager.GetString("StatusGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}... (archive&apos;s size is {1} MB, this will take some time).
        /// </summary>
        internal static string StatusInstallingBigModpack {
            get {
                return ResourceManager.GetString("StatusInstallingBigModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}....
        /// </summary>
        internal static string StatusInstallingGeneric {
            get {
                return ResourceManager.GetString("StatusInstallingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found in source directory..
        /// </summary>
        internal static string StatusSourceFileNotFound {
            get {
                return ResourceManager.GetString("StatusSourceFileNotFound", resourceCulture);
            }
        }
    }
}
